# Generated by Django 5.0 on 2025-12-06 09:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "filiere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATH", "Mathematiques"),
                            ("INFO", "Informatique"),
                            ("PHYSIQUE", "Physique"),
                            ("CHIMIE", "Chimie"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Epreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("matiere", models.CharField(max_length=100)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "type_epreuve",
                    models.CharField(
                        choices=[
                            ("PARTIEL", "Partiel"),
                            ("EXAMEN", "Examen"),
                            ("TD", "TD"),
                            ("RATTRAPAGE", "Rattrapage"),
                            ("CC", "Controle Continu"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "annee_academique",
                    models.CharField(help_text="Ex: 2023-2024", max_length=20),
                ),
                ("professeur", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fichier_pdf",
                    models.CharField(
                        help_text="Chemin ou URL du fichier PDF", max_length=500
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nb_vues", models.PositiveIntegerField(default=0)),
                ("nb_telechargements", models.PositiveIntegerField(default=0)),
                ("note_moyenne_difficulte", models.FloatField(default=0.0)),
                ("note_moyenne_pertinence", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Epreuve",
                "verbose_name_plural": "Epreuves",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["matiere", "niveau"],
                        name="core_epreuv_matiere_33bfdb_idx",
                    ),
                    models.Index(
                        fields=["annee_academique"],
                        name="core_epreuv_annee_a_70f88a_idx",
                    ),
                    models.Index(
                        fields=["-nb_telechargements"],
                        name="core_epreuv_nb_tele_ce05ed_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="core.epreuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_difficulte",
                    models.PositiveSmallIntegerField(
                        help_text="Note de difficulte de 1 (facile) a 5 (difficile)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "note_pertinence",
                    models.PositiveSmallIntegerField(
                        help_text="Note de pertinence de 1 (peu pertinent) a 5 (tres pertinent)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="core.epreuve",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation",
                "verbose_name_plural": "Evaluations",
                "ordering": ["-created_at"],
                "unique_together": {("user", "epreuve")},
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Consultation"),
                            ("DOWNLOAD", "Telechargement"),
                            ("CLICK", "Clic"),
                            ("RATE", "Evaluation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session_duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duree en secondes (pour VIEW)", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="core.epreuve",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_intera_user_id_440b61_idx",
                    ),
                    models.Index(
                        fields=["epreuve", "-timestamp"],
                        name="core_intera_epreuve_fc6c58_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="core_intera_action__cc09d9_idx",
                    ),
                ],
            },
        ),
    ]
