# Generated by Django 5.0 on 2026-01-06 09:33

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuve",
            name="hash_fichier",
            field=models.CharField(
                blank=True,
                help_text="Hash SHA-256 du fichier pour vérifier l'intégrité",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="epreuve",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Épreuve validée par un modérateur"
            ),
        ),
        migrations.AddField(
            model_name="epreuve",
            name="nb_pages",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="epreuve",
            name="taille_fichier",
            field=models.PositiveIntegerField(
                default=0, help_text="Taille du fichier en octets"
            ),
        ),
        migrations.AddField(
            model_name="epreuve",
            name="texte_extrait",
            field=models.TextField(
                blank=True, help_text="Texte extrait du PDF pour recherche full-text"
            ),
        ),
        migrations.AddField(
            model_name="epreuve",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="epreuves_uploadees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="fichier_pdf",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF de l'épreuve (max 10 MB)",
                null=True,
                upload_to=apps.core.models.epreuve_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="epreuve",
            index=models.Index(
                fields=["is_approved"], name="core_epreuv_is_appr_c0e6d5_idx"
            ),
        ),
    ]
