# Generated by Django 5.0 on 2026-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_pdf_file_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("P1", "Prépa 1"),
                    ("P2", "Prépa 2"),
                    ("L3", "Licence 3"),
                    ("M1", "Master 1"),
                    ("M2", "Master 2"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="filiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MATH", "Mathematiques"),
                    ("INFO", "Informatique"),
                    ("PHYSIQUE", "Physique"),
                    ("CHIMIE", "Chimie"),
                    ("RO", "Recherche Opérationnelle"),
                    ("STAT_PROB", "Statistique et Probabilité"),
                    ("MATH_FOND", "Mathématique Fondamentale"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="niveau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1", "Prépa 1"),
                    ("P2", "Prépa 2"),
                    ("L3", "Licence 3"),
                    ("M1", "Master 1"),
                    ("M2", "Master 2"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
