# Generated by Django 5.0 on 2026-02-28 13:00

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_replace_l1_l2_with_prepa_add_new_filieres"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_profil",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil (JPG, PNG, max 5 MB)",
                null=True,
                upload_to=apps.core.models.profile_photo_path,
            ),
        ),
    ]
