# Generated by Django 5.0 on 2026-04-02 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_photo_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="niveau_difficulte_ressenti",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Difficulté ressentie (1=très facile, 5=très difficile)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="note_utilite",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="À quel point cette épreuve vous a été utile (1=pas utile, 5=très utile)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="recommande",
            field=models.BooleanField(
                blank=True,
                help_text="Recommanderiez-vous cette épreuve à d'autres étudiants ?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("VIEW", "Consultation"),
                    ("DOWNLOAD", "Telechargement"),
                    ("CLICK", "Clic"),
                    ("RATE", "Evaluation"),
                    ("COMMENT", "Commentaire"),
                    ("BOOKMARK", "Favori"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="commentaire",
            index=models.Index(
                fields=["epreuve", "-created_at"], name="core_commen_epreuve_3e5b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentaire",
            index=models.Index(
                fields=["user", "-created_at"], name="core_commen_user_id_37dcc8_idx"
            ),
        ),
    ]
