# Generated by Django 5.0 on 2026-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_commentaire_niveau_difficulte_ressenti_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epreuve",
            name="professeur",
        ),
        migrations.AlterField(
            model_name="epreuve",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Épreuve approuvée (toujours True)"
            ),
        ),
    ]
