# Generated by Django 5.0 on 2026-04-02 19:45

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_professeur_auto_approve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epreuve",
            name="fichier_pdf",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF de l'épreuve (max 10 MB)",
                max_length=500,
                null=True,
                upload_to=apps.core.models.epreuve_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
