# Generated by Django 5.0 on 2025-12-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("model_path", models.CharField(max_length=500)),
                ("architecture", models.CharField(default="NCF", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("hyperparameters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Metadata du modele",
                "verbose_name_plural": "Metadatas des modeles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_date", models.DateTimeField(auto_now_add=True)),
                (
                    "training_duration",
                    models.PositiveIntegerField(help_text="Duree en secondes"),
                ),
                ("nb_interactions", models.PositiveIntegerField()),
                ("nb_users", models.PositiveIntegerField()),
                ("nb_epreuves", models.PositiveIntegerField()),
                ("train_loss", models.FloatField()),
                ("val_loss", models.FloatField()),
                ("test_loss", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField()),
                ("precision_at_10", models.FloatField()),
                ("recall_at_10", models.FloatField()),
                ("ndcg_at_10", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_logs",
                        to="recommender.modelmetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'entrainement",
                "verbose_name_plural": "Logs d'entrainement",
                "ordering": ["-training_date"],
            },
        ),
    ]
